config/routes.rb
Rails.application.routes.draw do

  root 'jobs#home'
  devise_for  :users, 
              :path => '', 
              :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
              :controllers => {:omniauth_callbacks => 'omniauth_callbacks',
                                :registrations => 'registrations'
                              }
  resources :jobs do
    puts :update_status  
    resources :bids, shallow: true
  end

  resources :users, only: [:show]

  resources :job_skills

  resources :users, only: [:show] do
    resources :skills do
      resources :votes
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  acts_as_taggable
  acts_as_taggable_on :skills
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :identities
  has_many :bids
  has_many :jobs
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable
         
  validates :fullname, presence: true, length: {maximum: 50}
  # validates :email, uniqueness: true, allow_nil: true

  has_many :skills
  has_many :votes
  serialize :user_skills

  def self.from_omniauth(auth)
  	user = User.where(email: auth.info.email).first

    if user
      return user
    else
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.fullname = auth.info.name
        user.provider = auth.provider
        user.uid = auth.uid
        user.email = auth.info.email
        user.image = auth.info.image
        user.password = Devise.friendly_token[0,20]
      end
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_users, only: [:show, :edit, :update, :destroy]

  def show
  end

	def set_users
		@user = User.find(params[:id])
	end
end

app/views/users/show.html.erb
<div class="row">
	<div class="col-md-3">
		<div class="center">
		<%= image_tag avatar_url(@user), class: "avatar-full" %>
	</div>
	<div class="panel panel-default">
		<div class="panel-heading">Verification</div>
		<div class="panel-body">
			Email Address<br>
			Phone Number
			</div>
		</div>
	</div>

	<div class="col-md-9">
		<h2><%= @user.fullname %></h2>

		<div class="description row-space-3">
			<%= @user.description %>
		</div>
	</div>
</div>
<strong>Jobs :</strong><br>
	<% @user.jobs.each do |job| %>
		<%= link_to job.name, job_path(job) %><br> 
	<%end%><br><br>

<strong>Skills :</strong><br> 
	<% @user.skills.each do |skill| %>
		<%= skill.skill %> 
			<% unless skill.user_id == current_user.id %>
				<% unless current_user.votes.exists?(skill.votes) %>
					<%= link_to("Like", user_skill_votes_path(current_user, skill, :up_vote => 1.to_i), :method => :post) %>
				<% end %>
				<% skill.votes.each do |vote|%>
					<% if vote.user_id == current_user.id %>
						<%= link_to("Unlike", user_skill_vote_path(current_user, skill, vote), :method => :delete) %>
				<% end %>	
			<% end %>
		<% end %>
		| <%= link_to Vote.where("skill_id = #{skill.id}", "up_vote = 1").count, user_skill_path(@user, skill) %><br>
	<% end %>