config/routes.rb
Rails.application.routes.draw do

  root 'jobs#home'
  devise_for  :users, 
              :path => '', 
              :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
              :controllers => {:omniauth_callbacks => 'omniauth_callbacks',
                                :registrations => 'registrations'
                              }
  resources :jobs do
    puts :update_status  
    resources :bids, shallow: true
  end

  resources :users, only: [:show]

  resources :job_skills

  resources :users, only: [:show] do
    resources :skills do
      resources :votes
    end
  end

end

app/views/shared/_devisemes.html.erb
<% unless resource.errors.empty? %>
	<script type="text/javascript">
		<% resource.errors.full_messages.each do |msg| %>
			toastr.error('<%= msg %>')
		<% end %>
	</script>
<% end %>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
	<script type="text/javascript">
		<% flash.each do |f| %>
			<% type = f[0].to_s.gsub('alert','error').gsub('notice','info') %>
			toastr['<%= type %>']('<%= f[1] %>')
		<% end %>
	</script>
<% end %>

app/views/shared/_navbar.html.erb
<!-- Fixed navbar -->
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">CONTRACTR</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if(!user_signed_in?) %>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <%= image_tag avatar_url(current_user), class: "img-circle avatar-small" %>&nbsp;
            <%= current_user.fullname %><span class="caret"></span></a>
            
            <ul class="dropdown-menu">
              <li><%= link_to "Create A Job", new_job_path %></li>
              <li><%= link_to "All Jobs", jobs_path %></li>
              <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "User Profile", user_path(current_user.id) %></li>
              <li><%= link_to "Messages",conversations_path %><li>
              <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>